version: '3.8'

# Skymmich Production Docker Compose Configuration
# Uses pre-built images from GitHub Container Registry
# 
# Quick start:
# 1. Copy .env.example to .env and configure your settings
# 2. docker compose -f docker-compose.prod.yml up -d
# 3. Access at http://localhost:5000

services:
  skymmich:
    image: ghcr.io/mstelz/skymmich:latest
    container_name: skymmich
    restart: unless-stopped
    ports:
      - "${SKYMMICH_PORT:-5000}:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://skymmich:${POSTGRES_PASSWORD}@skymmich-db:5432/skymmich
      - IMMICH_URL=${IMMICH_URL:-}
      - IMMICH_API_KEY=${IMMICH_API_KEY:-}
      - ASTROMETRY_API_KEY=${ASTROMETRY_API_KEY:-}
      - ENABLE_PLATE_SOLVING=${ENABLE_PLATE_SOLVING:-true}
      # Plate solving configuration
      - ASTROMETRY_CHECK_INTERVAL=${ASTROMETRY_CHECK_INTERVAL:-30}
      - ASTROMETRY_POLL_INTERVAL=${ASTROMETRY_POLL_INTERVAL:-5}
      - ASTROMETRY_MAX_CONCURRENT=${ASTROMETRY_MAX_CONCURRENT:-3}
      - ASTROMETRY_AUTO_RESUBMIT=${ASTROMETRY_AUTO_RESUBMIT:-false}
      - XMP_SIDECAR_PATH=/app/sidecars
    volumes:
      - skymmich-config:/app/config
      - skymmich-logs:/app/logs
      - skymmich-sidecars:/app/sidecars
    depends_on:
      skymmich-db:
        condition: service_healthy
    networks:
      - skymmich-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  skymmich-db:
    image: postgres:15-alpine
    container_name: skymmich-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=skymmich
      - POSTGRES_USER=skymmich
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - skymmich-database:/var/lib/postgresql/data
    networks:
      - skymmich-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skymmich -d skymmich"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # PostgreSQL port not exposed externally for security

networks:
  skymmich-network:
    driver: bridge

volumes:
  skymmich-config:
    driver: local
  skymmich-database:
    driver: local
  skymmich-logs:
    driver: local
  skymmich-sidecars:
    driver: local